### PR TITLE
Added methods add_tab, close_tab for working with multiple tabs. Adde…

### PR DESCRIPTION
**Pull request by marshygeek**
…d id parameter to Chrome_tab class for closing tabs properly.

### CODE REVIEW

**Comment by iiSeymour** [comment]
Hey @marshygeek can you rollback the latest commit and I'll get this merged in.

**Comment by marshygeek** [comment]
Is there some method to do that through github?

**Comment by marshygeek** [comment]
Done

**Comment by marshygeek** [comment]
I thought that commit with readme refers only to my local fork repository

**Comment by iiSeymour** [comment]
A pull request tracks the head of the branch to be merged so any commits on your forks master branch are included. Anyway, thanks for submitting this 👍

**Pull request merged**
